### ISSUE TITLE
Pod Runtime: Policy rules are empty in UI

### ISSUE THREAD

**Issue by kravciak** [kubewarden/pod-runtime-class-policy#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Policy rules are empty (and not editable in UI) so policy can't be created.  Finish button is disabled.

![Screenshot from 2023-02-10 09-00-02](https://user-images.githubusercontent.com/538604/218035508-b24eb6cb-7627-40dd-9eed-3717b596d35a.png)

**Comment by flavio** [comment]
ok, let me take a look at that

**Comment by flavio** [comment]
I think we have to move it into the blocked column, until we fix https://github.com/kubewarden/pod-runtime-class-policy/issues/15

**Comment by kravciak** [comment]
Fixed by rewrite to rust
